// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CdjW0yXD1inbO7txWxCbbaztH1zgB_s',
    appId: '1:743662220242:web:13d919deb0707ea22b0e0b',
    messagingSenderId: '743662220242',
    projectId: 'flutteruserinformationtest',
    authDomain: 'flutteruserinformationtest.firebaseapp.com',
    databaseURL: 'https://flutteruserinformationtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteruserinformationtest.appspot.com',
    measurementId: 'G-TTPGTNWMWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1KbGccUsZjSJWCBJ5qvU32Q1hrSqZ5MQ',
    appId: '1:743662220242:android:b3ff4ef26663e4e32b0e0b',
    messagingSenderId: '743662220242',
    projectId: 'flutteruserinformationtest',
    databaseURL: 'https://flutteruserinformationtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteruserinformationtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5dKlKRLUJwYM26Vx2QSU3N0Uq1BuWDk',
    appId: '1:743662220242:ios:6c4393e03329da2a2b0e0b',
    messagingSenderId: '743662220242',
    projectId: 'flutteruserinformationtest',
    databaseURL: 'https://flutteruserinformationtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteruserinformationtest.appspot.com',
    iosBundleId: 'com.example.flutterdatatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy5dKlKRLUJwYM26Vx2QSU3N0Uq1BuWDk',
    appId: '1:743662220242:ios:6c4393e03329da2a2b0e0b',
    messagingSenderId: '743662220242',
    projectId: 'flutteruserinformationtest',
    databaseURL: 'https://flutteruserinformationtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteruserinformationtest.appspot.com',
    iosBundleId: 'com.example.flutterdatatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CdjW0yXD1inbO7txWxCbbaztH1zgB_s',
    appId: '1:743662220242:web:d81755a893e50fc92b0e0b',
    messagingSenderId: '743662220242',
    projectId: 'flutteruserinformationtest',
    authDomain: 'flutteruserinformationtest.firebaseapp.com',
    databaseURL: 'https://flutteruserinformationtest-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutteruserinformationtest.appspot.com',
    measurementId: 'G-QHPSJ3J4BL',
  );
}
